import { NextRequest, NextResponse } from 'next/server'
import { adminAuth, adminDb } from '@/lib/firebase-admin'

export const dynamic = 'force-dynamic'
export const maxDuration = 60 // Allow up to 60 seconds for Gamma generation

export async function POST(request: NextRequest) {
  try {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader?.startsWith('Bearer ')) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const token = authHeader.split('Bearer ')[1]
    const decodedToken = await adminAuth.verifyIdToken(token)
    const userId = decodedToken.uid

    const body = await request.json()
    const { follower, analysisId } = body

    if (!follower || !follower.username) {
      return NextResponse.json({ 
        error: 'Missing follower data' 
      }, { status: 400 })
    }

    // Select theme based on follower category and priority
    const getThemeForFollower = (category: string, priority: string) => {
      // Tech/Business categories get professional themes
      if (category.toLowerCase().includes('tech') || category.toLowerCase().includes('engineer')) {
        return priority === 'HIGH' ? 'aurora' : 'midnight'
      }
      if (category.toLowerCase().includes('business') || category.toLowerCase().includes('entrepreneur')) {
        return 'corporate'
      }
      if (category.toLowerCase().includes('creator') || category.toLowerCase().includes('influencer')) {
        return 'vibrant'
      }
      if (category.toLowerCase().includes('media') || category.toLowerCase().includes('journalist')) {
        return 'modern'
      }
      // Default themes based on priority
      if (priority === 'HIGH') return 'aurora'
      if (priority === 'MEDIUM') return 'modern'
      return 'minimal'
    }

    const selectedTheme = getThemeForFollower(follower.category, follower.priority)

    // Create rich markdown content for Gamma
    const markdownContent = `# 📊 ${follower.name || follower.username}
## Follower Analysis Report

**@${follower.username}**

---

## 🎯 Overview

**Influence Score:** ${follower.influenceScore}/10  
**Category:** ${follower.category}  
**Priority:** ${follower.priority}  
**Engagement Level:** ${follower.engagementValue}

---

## 📊 Key Metrics

| Metric | Value |
|--------|-------|
| Influence Score | ${follower.influenceScore}/10 |
| Category | ${follower.category} |
| Priority Level | ${follower.priority} |
| Engagement Value | ${follower.engagementValue} |

---

## 💡 Why They Matter

${follower.strategicValue}

---

## ✨ Recommended Action

${follower.actionRecommendation}

---

*Generated by Followlytics AI Analysis*`

    // Store Gamma generation request
    const generationId = `gamma_follower_${Date.now()}_${Math.random().toString(36).substring(7)}`
    
    await adminDb.collection('gamma_reports').doc(generationId).set({
      userId,
      analysisId: analysisId || null,
      followerUsername: follower.username,
      followerData: follower,
      theme: selectedTheme,
      status: 'generating',
      createdAt: new Date(),
      type: 'individual_follower'
    })

    // Call Gamma API to actually generate the report
    if (process.env.GAMMA_API_KEY) {
      try {
        // Use Gamma's public API v0.2 endpoint (correct format)
        const gammaResponse = await fetch('https://public-api.gamma.app/v0.2/generations', {
          method: 'POST',
          headers: {
            'X-API-Key': process.env.GAMMA_API_KEY,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            inputText: markdownContent,
            textMode: 'preserve',
            format: 'document',
            textOptions: {
              language: 'en'
            }
            // Note: theme selection handled by Gamma's AI
          })
        })

        if (gammaResponse.ok) {
          const gammaData = await gammaResponse.json()
          const generationGammaId = gammaData.id || gammaData.generationId
          
          // Gamma API returns generation ID, need to poll for URL
          // Store generation ID and let frontend poll for completion
          await adminDb.collection('gamma_reports').doc(generationId).update({
            status: 'generating',
            gammaGenerationId: generationGammaId,
            statusUrl: `https://public-api.gamma.app/v0.2/generations/${generationGammaId}`,
            updatedAt: new Date()
          })
          
          console.log('[Gamma] Generation started:', {
            generationId,
            gammaGenerationId: generationGammaId,
            follower: follower.username,
            message: 'Frontend will poll for completion'
          })
          
          // Note: Frontend polls for completion via /api/gamma/status
          // This allows proper timeout handling and user feedback
        } else {
          const errorText = await gammaResponse.text()
          console.error('[Gamma] API error response:', {
            status: gammaResponse.status,
            statusText: gammaResponse.statusText,
            body: errorText,
            apiKey: process.env.GAMMA_API_KEY ? 'Present (hidden)' : 'Missing'
          })
          throw new Error(`Gamma API request failed: ${gammaResponse.status} - ${errorText}`)
        }
      } catch (gammaError: any) {
        console.error('[Gamma] Generation error:', {
          message: gammaError.message,
          stack: gammaError.stack,
          follower: follower.username
        })
        
        // Fall back to simulation with helpful message
        await adminDb.collection('gamma_reports').doc(generationId).update({
          status: 'completed',
          url: `https://gamma.app/docs/follower-analysis-${follower.username.toLowerCase()}-${generationId}`,
          completedAt: new Date(),
          note: `Simulated (API Error: ${gammaError.message}). This is a demo link. Add valid GAMMA_API_KEY to Vercel environment variables for real Gamma generation.`,
          isSimulated: true
        })
      }
    } else {
      console.log('[Gamma] No API key configured - using simulation mode')
      // No API key - simulate generation
      setTimeout(async () => {
        try {
          await adminDb.collection('gamma_reports').doc(generationId).update({
            status: 'completed',
            url: `https://gamma.app/docs/follower-analysis-${follower.username.toLowerCase()}-${generationId}`,
            completedAt: new Date(),
            note: 'Simulated - Add GAMMA_API_KEY to Vercel environment variables for real Gamma generation'
          })
        } catch (error) {
          console.error('Failed to update Gamma status:', error)
        }
      }, 5000)
    }

    return NextResponse.json({
      success: true,
      generationId,
      message: 'Gamma generation started'
    })

  } catch (error: any) {
    console.error('Generate follower Gamma error:', error)
    return NextResponse.json({ 
      error: 'Failed to generate Gamma',
      details: error.message 
    }, { status: 500 })
  }
}
