import { NextRequest, NextResponse } from 'next/server'
import { adminAuth, adminDb } from '@/lib/firebase-admin'

export const dynamic = 'force-dynamic'

export async function POST(request: NextRequest) {
  try {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader?.startsWith('Bearer ')) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const token = authHeader.split('Bearer ')[1]
    const decodedToken = await adminAuth.verifyIdToken(token)
    const userId = decodedToken.uid

    const body = await request.json()
    const { follower, analysisId } = body

    if (!follower || !follower.username) {
      return NextResponse.json({ 
        error: 'Missing follower data' 
      }, { status: 400 })
    }

    // Select theme based on follower category and priority
    const getThemeForFollower = (category: string, priority: string) => {
      // Tech/Business categories get professional themes
      if (category.toLowerCase().includes('tech') || category.toLowerCase().includes('engineer')) {
        return priority === 'HIGH' ? 'aurora' : 'midnight'
      }
      if (category.toLowerCase().includes('business') || category.toLowerCase().includes('entrepreneur')) {
        return 'corporate'
      }
      if (category.toLowerCase().includes('creator') || category.toLowerCase().includes('influencer')) {
        return 'vibrant'
      }
      if (category.toLowerCase().includes('media') || category.toLowerCase().includes('journalist')) {
        return 'modern'
      }
      // Default themes based on priority
      if (priority === 'HIGH') return 'aurora'
      if (priority === 'MEDIUM') return 'modern'
      return 'minimal'
    }

    const selectedTheme = getThemeForFollower(follower.category, follower.priority)

    // Create rich markdown content for Gamma
    const markdownContent = `# 📊 ${follower.name || follower.username}
## Follower Analysis Report

**@${follower.username}**

---

## 🎯 Overview

**Influence Score:** ${follower.influenceScore}/10  
**Category:** ${follower.category}  
**Priority:** ${follower.priority}  
**Engagement Level:** ${follower.engagementValue}

---

## 📊 Key Metrics

| Metric | Value |
|--------|-------|
| Influence Score | ${follower.influenceScore}/10 |
| Category | ${follower.category} |
| Priority Level | ${follower.priority} |
| Engagement Value | ${follower.engagementValue} |

---

## 💡 Why They Matter

${follower.strategicValue}

---

## ✨ Recommended Action

${follower.actionRecommendation}

---

*Generated by Followlytics AI Analysis*`

    // Store Gamma generation request
    const generationId = `gamma_follower_${Date.now()}_${Math.random().toString(36).substring(7)}`
    
    await adminDb.collection('gamma_reports').doc(generationId).set({
      userId,
      analysisId: analysisId || null,
      followerUsername: follower.username,
      followerData: follower,
      theme: selectedTheme,
      status: 'generating',
      createdAt: new Date(),
      type: 'individual_follower'
    })

    // Call Gamma API to actually generate the report
    if (process.env.GAMMA_API_KEY) {
      try {
        const gammaResponse = await fetch('https://api.gamma.app/api/v1/generate', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${process.env.GAMMA_API_KEY}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            text: markdownContent,
            theme: selectedTheme,
            title: `${follower.name || follower.username} - Follower Analysis`
          })
        })

        if (gammaResponse.ok) {
          const gammaData = await gammaResponse.json()
          
          // Update with real Gamma URL
          await adminDb.collection('gamma_reports').doc(generationId).update({
            status: 'completed',
            url: gammaData.url || gammaData.share_url,
            gammaId: gammaData.id,
            completedAt: new Date()
          })
        } else {
          throw new Error('Gamma API request failed')
        }
      } catch (gammaError: any) {
        console.error('Gamma API error:', gammaError)
        // Fall back to simulation
        await adminDb.collection('gamma_reports').doc(generationId).update({
          status: 'completed',
          url: `https://gamma.app/docs/follower-analysis-${follower.username.toLowerCase()}-${generationId}`,
          completedAt: new Date(),
          note: 'Simulated - Add GAMMA_API_KEY to use real Gamma generation'
        })
      }
    } else {
      // No API key - simulate generation
      setTimeout(async () => {
        try {
          await adminDb.collection('gamma_reports').doc(generationId).update({
            status: 'completed',
            url: `https://gamma.app/docs/follower-analysis-${follower.username.toLowerCase()}-${generationId}`,
            completedAt: new Date(),
            note: 'Simulated - Add GAMMA_API_KEY to Vercel environment variables for real Gamma generation'
          })
        } catch (error) {
          console.error('Failed to update Gamma status:', error)
        }
      }, 5000)
    }

    return NextResponse.json({
      success: true,
      generationId,
      message: 'Gamma generation started'
    })

  } catch (error: any) {
    console.error('Generate follower Gamma error:', error)
    return NextResponse.json({ 
      error: 'Failed to generate Gamma',
      details: error.message 
    }, { status: 500 })
  }
}
